### ISSUE TITLE
Issues installing SkinDetector on Windows 7 for python 2.7

### ISSUE THREAD

**Issue by phanig** [WillBrennan/SkinDetector#1]
Thank you so much for this repository, I'm curious about your skin detection library and having issues installing it. Please check out the screen shot attached. 

I'd appreciate if you can please share me your email address for any potential collaboration. My email address is contact(at)phanig.com

![image](https://cloud.githubusercontent.com/assets/2335819/8973782/31817790-361e-11e5-9f97-2c8f03ded403.png)

**Comment by WillBrennan** [comment]
Hi Phaneendra,

From the looks of it your current working directory is within the SkinDetector module, as such it can’t be imported by python as a module. Try moving your current working directory to SkinDetectors parent directory (C:\Users\gullaph\Documents\GitHub) and then you can import the SkinDetector module, it was designed to work as a git sub-module within a project. 

It does have a demo script within the module called main.py which works as a nice demonstration.

Hope this helps!

**Comment by phanig** [comment]
Thanks so much Will. It worked. Appreciate your prompt response. Again I was wondering if you can share your contact email address please ? I promise I won't spam you.

**Comment by WillBrennan** [comment]
Yeah sure, personal email is willbrennan0@gmail.com

**Comment by WillBrennan** [comment]
Issue Closed - SkinDetector was not cloned into the cwd.
