### ISSUE TITLE
B&W Mask

### ISSUE THREAD

**Issue by lkl015** [WillBrennan/SkinDetector#11]
Yo, Appreciate your work. 
However , when I try to use , I cannot produce the image shown in the demonstration.
My code : 
image = cv2.imread("path_of_img")
mask = skin_detector.process(image)
cv2.imwrite(os.path.expanduser("path_destination_result"), mask) 

The Image Input: 
![fff_background_removed](https://user-images.githubusercontent.com/32274059/30847473-4058a79c-a2ce-11e7-8bc4-42802eafc8b7.jpg)

The Image Output:
![skin](https://user-images.githubusercontent.com/32274059/30847480-457d6b36-a2ce-11e7-8e68-ada5d9299b8f.jpg)

However, I want to have the result output image to keep its original skin color , Please Help , Thanks so much !

**Comment by WillBrennan** [comment]
Hi there, 

It's relatively simple to do. Just do,

''' 
mask_rbg = cv2.bitwise_and(image, image, mask=mask) 
'''

and you should get the results you're after

**Comment by patrickwf** [comment]
Hi,Appreciate your work.
When I used your code, I found a small problem about function “def find_images(path, recursive=False, ignore=True)”
 if os.path.exists(path):#if i give a dir ,here is true ,and will never into “elif os.path.isdir(path)”
        yield path
    elif os.path.isdir(path):
     ......
    else:
        raise ValueError('error! path is not a valid path or directory')

so i modify your code like:

 if os.path.isdir(path):
   ......
    elif os.path.exists(path):
        yield path
    else:
        raise ValueError('error! path is not a valid path or directory')

ps: In my test, the result is not very good,do you have any better  algorithm? Thanks

**Comment by WillBrennan** [comment]
@patrickwf - You're 100% correct, that was supposed to be `isfile` not `ispath`. I've fixed that. If you're having issues with the detector I'd suggest checking that the colours and brightnesses are correct in the image. You can use something like,

```python
img_yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
img_yuv[:,:,0] = cv2.equalizeHist(img_yuv[:,:,0])
img = cv2.cvtColor(img_yuv, cv2.COLOR_YUV2BGR)
```
, to fix the brightness. If the images look correct then you could look into using newer techniques such as semantic segmentation using encoder-decoder networks.
