### ISSUE TITLE
Black and White Output

### ISSUE THREAD

**Issue by Valdecy** [WillBrennan/SkinDetector#14]
Hello William! Congratulations, this is a wonderfull script. Well I found something interesting and related with the issue #11 . Every time the program runs, it outputs a mask with only one chanel. That's why it generates black and white images.  This is intentional? Thank you very much for this library!

**Comment by WillBrennan** [comment]
Yes, it's generating a mask. You need to apply a bitwise operator to produce a coloured image. You can find more on stackoverflow.

[StackOverflow - opencv-apply-mask-to-a-color-image](https://stackoverflow.com/questions/10469235/opencv-apply-mask-to-a-color-image/38493075)
