### ISSUE TITLE
Bug about color space

### ISSUE THREAD

**Issue by fga401** [WillBrennan/SkinDetector#17]
I am using `opencv 4.2` and not sure whether it's a bug on early version.

I found that the returned HSV mask was almost empty (all zero), so I went deep into the codes and found 2 problems.

1. The default color space of opencv is BGR, so the second parameter of `cvtColor` should be  `COLOR_BGR2HSV`/`COLOR_BGR2YCrCb`. Accordingly, the threshold of YCrCb should also change to [90, 130, 100] ~ [230, 180, 120] (swap Cr and Cb channel)

2. The upper threshold of HSV may be [20, 150, 255]. H channel from 0 to 120 is too wide. The range of H channel in opencv is 0~180.

**Comment by WillBrennan** [comment]
Hi; 
This project hasn't actively been worked on in about five years and has been replaced by [SemanticSegmentation](https://github.com/WillBrennan/SemanticSegmentation). 

You're right on 1, its a bug on line [line 21](https://github.com/WillBrennan/SkinDetector/blob/master/skin_detector/skin_detector.py#L21), it should be `cv2.COLOR_BGR2...` and the thresholds should then be swapped around. 

On 2, I agree the range of hues is far too high and should be tighter. I'd need to revisit it to work out what a good range of hues should be.
