### ISSUE TITLE
Way to increase sensitivity 

### ISSUE THREAD

**Issue by timothyclemansinsea** [WillBrennan/SkinDetector#2]
I'm using this for video redaction of body parts. Could you please add a way to increase sensitivity?

**Comment by WillBrennan** [comment]
Hi - This feature already exists through the threshold argument, its default value is `0.5`, if you decrease the threshold value you should increase sensitivity. It might behave erratically though, as there's only three different generators, `get_mask_hsv`, `get_mask_rgb`, and `get_mask_ycrcb`. 

https://github.com/WillBrennan/SkinDetector/blob/master/scripts.py#L59

**Comment by timothyclemansinsea** [comment]
I changed threshold to 0.1 in the code as I couldn't figure out how to call process within Python script with argument for threshold. I used this video https://www.youtube.com/watch?v=3ClCvEvGzc8 and almost no skin was detected.

**Comment by WillBrennan** [comment]
So looking at that video the entire video seems to have some weird saturation and isn't true color. This method depends on color thresholding and not upon feature recognition. Perhaps trying something like converting to YCrCB pixel format, applying cv2.equaliseHistogram to the Y Channel, then convert back to RGB might get the video closer to true color?

**Comment by timothyclemansinsea** [comment]
Thank you for helping me yesterday. I was able to get pretty good results with it https://www.youtube.com/watch?v=egB54SZVFpg

**Comment by WillBrennan** [comment]
Nice! If you're trying to blur out just faces it might be worth looking at the link below. Can't be used for commercial purposes though.

http://docs.opencv.org/master/d7/d8b/tutorial_py_face_detection.html#gsc.tab=0

**Comment by timothyclemansinsea** [comment]
I found face detection and manual object tracking failed too much. For dashcam I use subtraction from a reference frame https://www.youtube.com/watch?v=LJNDTUKwT94 and for bodycam trying to use color range.

**Comment by WillBrennan** [comment]
Can I just ask, what's this project for?

**Comment by timothyclemansinsea** [comment]
It's for
http://www.theguardian.com/us-news/2015/mar/09/seattle-police-posting-body-camera-footage-youtube-transparency
Trying to come up with a reliable blur all persons scheme for dash and body
cam videos so that Seattle Police can post that footage on Youtube.

**Comment by WillBrennan** [comment]
Nice! Hope it helps, seems like a very worth while project. Feel free to make pull requests if you come up with any improvements, it'd be much appreciated.
