### ISSUE TITLE
Error in main.py

### ISSUE THREAD

**Issue by alvarouc** [WillBrennan/SkinDetector#3]
I am runing opencv 3.0, python 3.5 in ubuntu 16.04

When I run:
python main.py ~/MovieProcessing/alvaro/delete/p6-1.png --display

here is the image 
![p6-1](https://cloud.githubusercontent.com/assets/7969170/21193976/6c13d2e0-c1eb-11e6-9ca1-7810cefd8e24.png)

I get the error

OpenCV Error: Sizes of input arguments do not match (The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array') in binary_op, file /home/aulloa/src/opencv/modules/core/src/arithm.cpp, line 225
Traceback (most recent call last):
  File "main.py", line 197, in <module>
    img_msk = process(img_col, args=args)
  File "main.py", line 188, in process
    return detector.process(image)
  File "main.py", line 125, in process
    self.get_mask_rgb(img)
  File "main.py", line 61, in get_mask_rgb
    msk_rgb = cv2.bitwise_and(mask_a, mask_b)
cv2.error: /home/aulloa/src/opencv/modules/core/src/arithm.cpp:225: error: (-209) The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array' in function binary_op

**Comment by WillBrennan** [comment]
Hi;

I believe this is a problem with OpenCV 3.X, I've only run it on 2.7. I'd suggest that you check if the interface for cv2.bitwise_and has changed.

**Comment by alvarouc** [comment]
It has the same functionality. I think the problem comes from tha data type of mask_a or mask_b.

**Comment by Clemence-ECL** [comment]
@alvarouc Hi, 
Have you reached to fix it ?

**Comment by alvarouc** [comment]
I don't know how to fix it. I ended up building a custom solution.

**Comment by WillBrennan** [comment]
@Clemence-ECL 
Hey, 
About six months ago I cleaned up quiet a bit of the skin detector code. Just wondering what problems you're having?

**Comment by parth1993** [comment]
@WillBrennan 
Hey,
Just found the issue and updated the code. Now there would be no issue it running on python3 also.

**Comment by WillBrennan** [comment]
Issue fixed in #9
